import type { Metadata } from "next";
import Navbar from "./Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{display : "grid" , gridTemplateColumns : "300px 1fr" , gap : "20px"}}>
           <div style={{ background : "red"}}> <h1>sidebare</h1></div>
           <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
